version: "3"

volumes:
  redis:

services:
  traefik:
    image: "traefik:latest"
    command:
      - "--providers.docker"
      - "--providers.file.directory=/etc/traefik/dynamic_conf"
      - "--entrypoints.http.address=:80"
      - "--entrypoints.https.address=:443"
      - "--providers.docker.exposedByDefault=false"
      - "--certificatesResolvers.le.acme.email=contact@zekro.de"
      - "--certificatesResolvers.le.acme.storage=/etc/certstore/acme.json"
      - "--certificatesResolvers.le.acme.httpChallenge.entryPoint=http"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./traefik/config:/etc/traefik/dynamic_conf"
      - "./traefik/certstore:/etc/certstore"
    restart: "on-failure"

  redis:
    image: "redis:alpine"
    expose:
      - "6379"
    volumes:
      - "redis:/data"
    command:
      - "--appendonly yes"

  lookupex:
    build:
      context: "."
      dockerfile: "Dockerfile"
    image: "ghcr.io/zekrotja/lookupex:latest"
    expose:
      - "8080"
    environment:
      REDIS_ADDRESS: "redis://redis:6379/1"
      DISCORD_API_TOKEN: "NDE5ODM3NDcyMDQ2ODQxODY2.WpvqHQ.fvm_JfeRw0XNrqxVAOFvXVKDfiM"
    depends_on:
      - "redis"
    labels:
      traefik.enable: "true"
      traefik.http.routers.lookupex-api.entrypoints: "http"
      traefik.http.routers.lookupex-api.tls: "true"
      traefik.http.routers.lookupex-api.tls.certresolver: "le"
      traefik.http.routers.lookupex-api.rule: "Host(`lookup.example.com`) && PathPrefix(`/api`)"
      traefik.http.routers.lookupex-api.middlewares: "lookupex-api-rl,lookupex-api-sp"
      traefik.http.middlewares.lookupex-api-rl.ratelimit.average: "10"
      traefik.http.middlewares.lookupex-api-rl.ratelimit.period: "1m"
      traefik.http.middlewares.lookupex-api-rl.ratelimit.burst: "10"
      traefik.http.middlewares.lookupex-api-sp.stripprefix.prefixes: "/api"

  webapp:
    build:
      context: "."
      dockerfile: "./webapp/Dockerfile"
      args:
        - "API_ENDPOINT=https://lookup.example.com/api"
    image: "webapp:latest"
    expose:
      - "80"
    depends_on:
      - "redis"
    labels:
      traefik.enable: "true"
      traefik.http.routers.lookupex-api.entrypoints: "http"
      traefik.http.routers.lookupex-api.tls: "true"
      traefik.http.routers.lookupex-api.tls.certresolver: "le"
      traefik.http.routers.lookupex-api.rule: "Host(`lookup.example.com`)"
